models/Auto.php
<?php

namespace app\models;

use Yii;
use yii\web\UploadedFile;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "auto".
 *
 * @property int $id
 * @property int $brand
 * @property int $car_model
 * @property int $engine_type
 * @property int $drive_unit
 *
 * @property Brand $brand0
 * @property CarModel $carModel
 * @property DriveUnit $driveInit
 * @property EngineType $engineType
 */
class Auto extends \yii\db\ActiveRecord
{
    public $imageFiles;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'auto';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['brand', 'car_model', 'engine_type', 'drive_unit'], 'required'],
            [['brand', 'car_model', 'engine_type', 'drive_unit'], 'integer'],
            [['brand'], 'exist', 'skipOnError' => true, 'targetClass' => Brand::className(), 'targetAttribute' => ['brand' => 'id']],
            [['car_model'], 'exist', 'skipOnError' => true, 'targetClass' => CarModel::className(), 'targetAttribute' => ['car_model' => 'id']],
            [['drive_unit'], 'exist', 'skipOnError' => true, 'targetClass' => DriveUnit::className(), 'targetAttribute' => ['drive_unit' => 'id']],
            [['engine_type'], 'exist', 'skipOnError' => true, 'targetClass' => EngineType::className(), 'targetAttribute' => ['engine_type' => 'id']],
            [['imageFiles'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, gif', 'maxSize' => 1024 * 1024],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'brand' => 'Brand',
            'car_model' => 'Car Model',
            'engine_type' => 'Engine Type',
            'drive_unit' => 'Drive Init',
        ];
    }

    /**
     * Gets query for [[Brand0]].
     *
     * @return \yii\db\ActiveQuery|BrandQuery
     */
    public function getBrand0()
    {
        return $this->hasOne(Brand::class, ['id' => 'brand']);
    }

    /**
     * Gets query for [[CarModel]].
     *
     * @return \yii\db\ActiveQuery|CarModelQuery
     */
    public function getCarModel()
    {
        return $this->hasOne(CarModel::class, ['id' => 'car_model']);
    }

    /**
     * Gets query for [[DriveInit]].
     *
     * @return \yii\db\ActiveQuery|DriveUnitQuery
     */
    public function getDriveUnit()
    {
        return $this->hasOne(DriveUnit::class, ['id' => 'drive_unit']);
    }

    /**
     * Gets query for [[EngineType]].
     *
     * @return \yii\db\ActiveQuery|EngineTypeQuery
     */
    public function getEngineType()
    {
        return $this->hasOne(EngineType::class, ['id' => 'engine_type']);
    }

    public function getImages0()
    {
        return $this->hasMany(Images::class, ['auto_id' => 'id']);
    }

    /**
     * Полный список имеющихся в таблице брендов
     * @return array
     */
    public static function getBrandList()
    {
        $data = static::find()->joinWith(['brand0'])
            ->select(['*'])
            ->orderBy('brand.name')->asArray()->all();
        return ArrayHelper::map($data, 'id', 'name');
    }

    /**
     * Список имещихся в таблице моделей для отмеченных брендов
     * @return array
     */
    public static function getModelList()
    {

        $brand = !empty(Yii::$app->request->queryParams['AutoSearch']['brand']) ? Yii::$app->request->queryParams['AutoSearch']['brand'] : null;
        if ($brand) {
            $data = static::find()->joinWith(['carModel'])
                ->select(['*'])
                ->andFilterWhere(['in', 'brand', $brand])
                ->orderBy('car_model.name')->asArray()->all();
        } else {
            $data = static::find()->joinWith(['carModel'])
                ->select(['*'])
                ->orderBy('car_model.name')->asArray()->all();
        }

        return ArrayHelper::map($data, 'id', 'name');
    }

    /**
     * {@inheritdoc}
     * @return AutoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AutoQuery(get_called_class());
    }
}

controllers/AutoController.php
<?php

namespace app\controllers;

use app\models\CarModel;
use Yii;
use app\models\Auto;
use app\models\AutoSearch;
use app\models\AutoQuery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use bupy7\ajaxfilter\AjaxFilter;

/**
 * AutoController implements the CRUD actions for Auto model.
 */
class AutoController extends Controller
{

    /**
     * Lists all Auto models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AutoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Заполнение таблиц новыми данными
     * @return \yii\web\Response
     * @throws \yii\db\Exception
     */
    public function actionGenerate()
    {
        $model = new AutoQuery(Auto::class);
        if($model->generate()){
            Yii::$app->session->setFlash('success', 'Данные обновлены.');
        }else{
            Yii::$app->session->setFlash('error', 'Данные не обновлены. Ошибка транзацакции');
        }
        return $this->redirect(['index']);
    }

    /**
     * Набор моделей для отмеченных брендов
     */
    public function actionModels()
    {
        $id = Yii::$app->request->post('id');
        $models = !empty(Yii::$app->request->post('models')) ? Yii::$app->request->post('models') : [];
        $html = '';
        if ($id) {
            $operations = Auto::find()
                ->select(['*', 'car_model.id'])
                ->joinWith(['carModel'])
                ->andFilterWhere(['in', 'brand', $id])
                ->distinct()
                ->all();

        } else {
            $operations = Auto::find()
                ->select(['*', 'car_model.id'])
                ->joinWith(['carModel'])
                ->distinct()
                ->all();
        }
        if ($operations) {
            foreach ($operations as $operation) {
                if(in_array($operation->carModel->id, $models) && $id){
                    $html .= '<label><input type="checkbox" name="AutoSearch[car_model][]" value="' . $operation->carModel->id . '" checked>' . $operation->carModel->name . '</label>';
                }else{
                    $html .= '<label><input type="checkbox" name="AutoSearch[car_model][]" value="' . $operation->carModel->id . '">' . $operation->carModel->name . '</label>';
                }
            }
        }
        return $html;
    }
}

views/auto/_list.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>
<div class="news-item span4" style="float: left">
    <div class="card" style="width: 18rem;">
        --------------------------------
        <div class="card-body">
            <h4 class="card-title">Бренд: <?= Html::encode($model->brand0->name) ?></h4>
            <p class="card-text">Модель: <?= Html::encode($model->carModel->name) ?></p>
            <p class="card-text">Двигатель: <?= Html::encode($model->engineType->name) ?></p>
            <p class="card-text">Привод: <?= Html::encode($model->driveUnit->name) ?></p>
        </div>
    </div>
</div>

views/auto/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use app\models\EngineType;

/* @var $this yii\web\View */
/* @var $model app\models\AutoSearch */
/* @var $form yii\widgets\ActiveForm */
$url = Url::to('models');
$this->registerJs(<<<JS
//Функция фильтрования
function pjaxSend(){
    var brahds = [];
    var engine = [];
    var drive = [];
    var model = [];
    $.each($('#autosearch-brand input:checked'), function(index,value) {
        brahds.push($(value).val());        
    });
    $.each($('#autosearch-engine_type input:checked'), function(index,value) {
        engine.push($(value).val());        
    });    
    $.each($('#autosearch-drive_unit input:checked'), function(index,value) {
        drive.push($(value).val());        
    });
    $.each($('#SelectModel input:checked'), function(index,value) {
        model.push($(value).val());        
    });
    $.pjax({
        timeout: 4000,
        url: $('#filter-form').attr('action'),
        container: '#list-view',
        fragment: '#list-view',
        data: {AutoSearch: {brand:brahds, engine_type:engine, drive_unit:drive, car_model:model}},
   });
} 
//Фильтр по событию
$(document).on('change', '#filter-form input', function(e) {
    if($(this).hasClass('brand-input')){
        var brahds = [];        
        $.each($('#autosearch-brand input:checked'), function(index,value) {
            brahds.push($(value).val());        
        });
        var mod = [];
        $.each($('#SelectModel input:checked'), function(index,value) {
            mod.push($(value).val());        
        });
        console.log(mod)
        $.post( 
            '/auto/models',
            {id:brahds, models:mod}
        ).done(function( data ) {
            $('#SelectModel').html(data);
            pjaxSend();
        });
    }else {
        pjaxSend();
    }   
});
//сброс фильтра
$(document).on('click', '#reset', function(e) {
    e.preventDefault();
    $.post( 
            '/auto/models',
            {id:{}})
    .done(function( data ) {
            $('#SelectModel').html(data);
            $( "#filter-form input" ).prop( "checked", false );
            $.pjax({
                timeout: 4000,
                url: $('#filter-form').attr('action'),
                container: '#list-view',
                fragment: '#list-view',
                data: {}
            });
    });
});
JS
    , yii\web\View::POS_END);

?>

<div class="auto-search">
    <p>Фильтр</p>
    <?php yii\widgets\Pjax::begin(['id' => 'search']) ?>
    <?php $form = ActiveForm::begin([
        'id' => 'filter-form',
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'brand')->checkboxList(
        \app\models\Auto::getBrandList(),
        ['itemOptions' => ['class' => 'brand-input'],
        ]
    )->label('Бренды') ?>

    <?= $form->field($model, 'car_model')->checkboxList(
        \app\models\Auto::getModelList(),
        [
            'prompt' => 'Выберите бренд',
            'id' => 'SelectModel'
        ]
    )->label('Модели') ?>

    <?= $form->field($model, 'engine_type')->checkboxList(
        ArrayHelper::map(EngineType::find()->select(['id', 'name'])->asArray()->all(), 'id', 'name')
    )->label('Двигатель') ?>

    <?= $form->field($model, 'drive_unit')->checkboxList(
        ArrayHelper::map(app\models\DriveUnit::find()->select(['id', 'name'])->asArray()->all(), 'id', 'name')
    )->label('Привод') ?>

    <div class="form-group">
        <?= Html::a('Сброс фильтра', ['#'], ['id' => 'reset', 'class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <?php yii\widgets\Pjax::end() ?>

</div>

views/auto/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\widgets\PjaxAsset;
/* @var $this yii\web\View */
/* @var $searchModel app\models\AutoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
//PjaxAsset::register($this);
$this->title = 'Autos';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="auto-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::a('Обновить данные', ['generate'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php Pjax::begin(); ?>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'options' => ['id'=>'list-view'],
        'itemOptions' => ['class' => 'item'],
        'layout' => "<div class='lst row'>{items}</div><div>{pager}</div>",
        'itemView' => '_list',
        'pager' => [
            'firstPageLabel' => 'first',
            'lastPageLabel' => 'last',
            'prevPageLabel' => 'previous',
            'nextPageLabel' => 'next',
            'maxButtonCount' => 3,
        ],
    ]) ?>
    <?php Pjax::end(); ?>
</div>